# Generated by Django 6.0.7 on 2026-07-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationsession',
            name='department',
        ),
        migrations.RemoveField(
            model_name='presentationsession',
            name='level',
        ),
    ]
