# Generated by Django 6.0.7 on 2026-07-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_presentationsession_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='presentationsession',
            name='title',
        ),
        migrations.AddField(
            model_name='presentationsession',
            name='weekly_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='core.weeklysession'),
        ),
    ]
